language: python

cache: pip

python:
  - '2.7'
  - '3.6'
  - '3.7'
  - '3.8'

before_install:
  - travis_retry pip install --upgrade pip setuptools wheel coveralls

install:
  - travis_retry pip install -e .[tests]

script:
  - pytest --cov=hepdata_cli

after_success:
  - coveralls

deploy:
  skip_existing: true
  provider: pypi
  username: "__token__"
  password:
    secure: "jX3kx2wznVDW8NHaUo0pmRMJNcep1TFM8WN0BI56GLylhlCupx+L1ejTf/qdUdmydUz5P5vjFs5byzQZZi1Gm9FcoWXuos069XFZ+Ps7TAQXzGUWAxUarThOZUynhbco4kutf6X7DmQEZktAT56z1KkjorJg4ZrA/JF3OjD2Moz0R+qHxVohRCREKrDp0hqvs/EsvsWBLRPgtu6LzFxSpQUtKuSXDYEAoXhJN6RjyFnXhJdx1ARWPdFEXs+mDvnr3oDuUQCyKrwAFoYpWiKTiGxrT4NUHIQdtM70itvVw9AX1VMcyubWmrvJ3vHe3wIwzszGlGe7B/9SywVJokjIHS9wJ7BGVnek4s+zncUrOHZbxaJmd0yHIcAkXclX7p7UCnRPO7IkhKmmTgv5SDLAlXG3KBKuvrPCWsFU79X3nk4vF1qh6vGFphuTmKTa+6lSSiElcZ8IEkPWUto4UvR7bLOYv815PTAlCib4IOBzzVdwyA2fzWXRWbTEhL8bFnLXS2BbltByt0XVGdHdvxa/1Ys2+yCh+qqsZ+aamex18m9iRs1MLtwR2BeNK2JzI2dyAr/hQFrR0qk8/8qqFkZLpQIMDzpltDq6nlG2Cv7kZufmNsYpfd1ZfEGEHsUdtHdA5+ur6IlzPtiyt0nv8llxkhpxNf1gMxJGMHgYEeVm9sI="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: HEPData/hepdata-cli
  edge: true  # opt in to dpl v2